### ISSUE TITLE
section6 code files content can not be downloaded

### ISSUE THREAD

**Issue by oviis** [mspaulding06/pork#1]
Hi Matthew, 
I have purchase the video "GoBuilding DevOps Tools" from Packt. A very interesting Video, very much thanks for that. 
But when I try to download the code files, the section code 6 could not be downloaded as whole part.

I have tried with Firefox and Chrome but have the same issue. I have attached also a screenshot, to show how it looks like on my machine.

Could you please provide this code files again over Packt or over github?

![image](https://user-images.githubusercontent.com/6278038/36690565-f6ad6726-1b32-11e8-840e-44dd53c08676.png)

**Comment by mspaulding06** [comment]
Thank you for making me aware of the problem.  I've contacted the publisher and will hopefully have the issue resolved soon.

**Comment by mspaulding06** [comment]
After checking with the publisher there is no code to be downloaded for section 6 of the course.  All code provided here in the GitHub repository should be everything that you need for section 6.  If you find that anything is missing please let me know and I will add it.

Best Regards,
Matt

**Comment by oviis** [comment]
Hi,
Yes, I still missing the section6 of the course! It is a broken zip file, that can not be downloaded!
Without this section the whole Video and course is unusable.

If you can be so kind and paste the go files with "Writing the Core Library" where you implement NAP with all the interfaces and routers.

Thanks&Cheers
Ovi

**Comment by oviis** [comment]
Hi Matt,
thanks, but you can see I am not the only one, that have the same problem.
https://github.com/mspaulding06/nap/issues/1
Thanks in advance
Ovi

**Comment by oviis** [comment]
Hi Matt, 
in my opinion this issue is not resolved
Cheers
Ovi
